const note = [
  "Hello Gorgeous!",
  "Remember the note I was supposed to write in your book before you left?",
  "Well, here it is...",
  "It's been on my mind for a while now, and I've been trying to put this together for the past few days",
  "But my work has been getting in the way 😅",
  "This is the reason I didn't put up more of a challenge concerning the book 🌚",
  "Next time I won't go so easy on you 😂🤞🏽",
  "I'm very proud of you though 😊",
  "The whole point was for you to finish the book...and you did!",
  "You really deserve those heels you wanted 😂🤝🏽",
  "Anyways, on to the note...",
  "I don't really know how to put this 😶",
  "But here goes nothing 🤞🏽",
  "I guess I've always liked you since the beginning",
  "The more time I spent with you, the stronger I felt 💘",
  "Over time, I just longed to see you every day",
  "I lived for the moments you walked into the study room with that beautiful smile on your face",
  "Seriously though, what charm did you place on me?",
  "What spells did you cast?",
  'Suddenly, "no feelings mode" wasn\'t working anymore 🤣',
  "You really took up a lot of space in my mind...rent free 🌚",
  "Fast forward several months later and my feelings have only grown stronger ❤️",
  "I still think about you quite a lot",
  "Mostly fantasizing about spending time with you and thinking about ways to make you happy",
  "That's not creepy, is it? 😂💔",
  "Just wanted to let you know how much you mean to me",
  "Honestly, 2022 has been a hell of a ride for me, and you're without a doubt the best part of it all 💯",
  "As Paul said in Corinthians...",
  "Love endures with patience and serenity",
  "Love is kind and thoughtful",
  "Love is not jealous or envious",
  "Love is not proud or arrogant",
  "Love is not rude or self-seeking",
  "Love is not provoked, nor overly sensitive and easily angered",
  "Love does not take into account a wrong endured",
  "Love does not rejoice at injustice, but rejoices with the truth",
  "Love bears all things, regardless of what comes",
  "Love believes all things, looking for the best in each one",
  "Love hopes all things, remaining steadfast during difficult times",
  "Love endures all things, without weakening",
  "Love never fails. It never fades nor ends",
  "I think you know where this is going by now 😶😂",
  "I love you Bernice Bottey 💛",
  "I'm very glad to have you ✨",
  "Will you marry me? 🥺",
  "Ha! Just kidding 🤣",
  "At least for now 🤭",
  "I believe God is in this story ❤️",
  "Looking forward to a long, beautiful and happy life together 🥂",
  "Happy New Year to you and your family 🎉",
  "Enjoy the rest of the music🤞🏽",
  "Love, Paul 🙃",
];

export default note;
